Electron mvaID Fall17 V2
cbernet/cmg-cmssw pull request #6
Opened 2018-12-06 15:13 UTC by lucastorterotot

Use of the new code from Egamma implemented.

2018-12-07 15:20 UTC, lucastorterotot commented
New electronID interface, cleaned, based on a single method `electronID( str )`.

2018-12-10 08:05 UTC, cbernet requested changes
Salut Lucas,

Ca va dans la bonne direction, mais je pense qu'il faut revoir le design pour les raisons donnees dans mes commentaires. On peut en discuter si tu veux. 

Colin

2018-12-10 08:05 UTC, cbernet commented on PhysicsTools/Heppy/python/physicsobjects/Electron.py
> +    def electronID_category(self, id):
docstrings should be added to all methods, to precisely describe: 
- the inputs
- the returned value 
- what the function is doing

2018-12-10 08:05 UTC, cbernet commented on PhysicsTools/Heppy/python/physicsobjects/Electron.py
> +        if id.startswith("POG_Cuts_ID_"):
so why not just giving POG_ ?

2018-12-10 08:05 UTC, cbernet commented on PhysicsTools/Heppy/python/physicsobjects/Electron.py
> +            passed = self.electronIDs()[miniAODids.index(id)][1]
so in this case, score_raw and category are not set, and the returned values are inconsistent. 
This is a sign that this method is doing too much.

2018-12-10 08:05 UTC, cbernet commented on PhysicsTools/Heppy/python/physicsobjects/Electron.py
> +            raise RuntimeError("Electron id " + id + " not yet implemented in Electron.py, availables are: \n\n   from miniAOD:\n {miniAODids} \n\n   from FWLite:\n {Egamma} ".format(miniAODids=miniA
line is too long

2018-12-10 08:05 UTC, cbernet commented on PhysicsTools/Heppy/python/physicsutils/electronID_Egamma_dict.py
> +electronID_Egamma_dict = {
what is the need for this dict? are you tring with the keys to mimic strings that are in the miniaod? if yes this is good.

2018-12-10 08:05 UTC, cbernet commented on PhysicsTools/Heppy/python/physicsobjects/Electron.py
> +                passed = working_points[name].passed(self.physObj, score_raw, category, wp)
passed is evaluated even when the user does not ask for it, e.g. when calling electronID_score. 
Also, when using a given mva type, testing several working points for the same mva score requires re-evaluating the mva score (and getting the same results every time), which is not efficient and certainly slow. 
One should review the overall design to avoid this.

Please have a look at https://github.com/cbernet/cmg-cmssw/blob/htt_9_4_11_cand1_v1/PhysicsTools/Heppy/python/physicsobjects/Tau.py

and then we can discuss it. 
In the same way you should implement:
- mva_score
- mva_passes
- countWP
- electronID

In particular please note the caching of the mva scores here: https://github.com/cbernet/cmg-cmssw/blob/htt_9_4_11_cand1_v1/PhysicsTools/Heppy/python/physicsobjects/Tau.py#L32

2018-12-10 10:13 UTC, lucastorterotot commented on PhysicsTools/Heppy/python/physicsobjects/Electron.py
> +        if id.startswith("POG_Cuts_ID_"):
True. I let this as it was initially done in the previous version of the code. Now that this code aims at using directly the names stored in miniAODs, these lines can be removed.

2018-12-10 10:17 UTC, lucastorterotot commented on PhysicsTools/Heppy/python/physicsutils/electronID_Egamma_dict.py
> +electronID_Egamma_dict = {
Yes, the idea is to use only miniAODs names as input, and this dict translates to compute with FWLite if the key is not in the miniAOD.

2018-12-10 10:34 UTC, lucastorterotot commented on PhysicsTools/Heppy/python/physicsobjects/Electron.py
> +            raise RuntimeError("Electron id " + id + " not yet implemented in Electron.py, availables are: \n\n   from miniAOD:\n {miniAODids} \n\n   from FWLite:\n {Egamma} ".format(miniAODids=miniA
Modified, coming with the next PR.

2018-12-11 14:26 UTC, cbernet commented on PhysicsTools/Heppy/python/physicsutils/electronID_Egamma_dict.py
> +electronID_Egamma_dict_names = {
methods_dict 

and the above dict should be :  
wps_dict

2018-12-11 14:34 UTC, merged